version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: server
    container_name: server
    ports:
      - '8080:8080'
    depends_on: [db]

  db:
    image: mongo:latest
    container_name: db
    volumes: [database:/data/db/]
    ports:
      - '27017:27017'

volumes: { database }

